//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceNowWCF.JournalTableServiceNowReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.service-now.com", ConfigurationName="JournalTableServiceNowReference.ServiceNowSoap")]
    public interface ServiceNowSoap {
        
        // CODEGEN: Generating message contract since the operation insert is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/sys_journal_field/insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceNowWCF.JournalTableServiceNowReference.insertResponse1 insert(ServiceNowWCF.JournalTableServiceNowReference.insertRequest request);
        
        // CODEGEN: Generating message contract since the operation update is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/sys_journal_field/update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceNowWCF.JournalTableServiceNowReference.updateResponse1 update(ServiceNowWCF.JournalTableServiceNowReference.updateRequest request);
        
        // CODEGEN: Generating message contract since the operation deleteMultiple is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/sys_journal_field/deleteMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceNowWCF.JournalTableServiceNowReference.deleteMultipleResponse1 deleteMultiple(ServiceNowWCF.JournalTableServiceNowReference.deleteMultipleRequest request);
        
        // CODEGEN: Generating message contract since the operation getKeys is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/sys_journal_field/getKeys", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceNowWCF.JournalTableServiceNowReference.getKeysResponse1 getKeys(ServiceNowWCF.JournalTableServiceNowReference.getKeysRequest request);
        
        // CODEGEN: Generating message contract since the operation deleteRecord is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/sys_journal_field/deleteRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceNowWCF.JournalTableServiceNowReference.deleteRecordResponse1 deleteRecord(ServiceNowWCF.JournalTableServiceNowReference.deleteRecordRequest request);
        
        // CODEGEN: Generating message contract since the operation get is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/sys_journal_field/get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceNowWCF.JournalTableServiceNowReference.getResponse1 get(ServiceNowWCF.JournalTableServiceNowReference.getRequest request);
        
        // CODEGEN: Generating message contract since the operation getRecords is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/sys_journal_field/getRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceNowWCF.JournalTableServiceNowReference.getRecordsResponse getRecords(ServiceNowWCF.JournalTableServiceNowReference.getRecordsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class insert : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string elementField;
        
        private string element_idField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
                this.RaisePropertyChanged("element");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string element_id {
            get {
                return this.element_idField;
            }
            set {
                this.element_idField = value;
                this.RaisePropertyChanged("element_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class insertResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sys_idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.insert insert;
        
        public insertRequest() {
        }
        
        public insertRequest(ServiceNowWCF.JournalTableServiceNowReference.insert insert) {
            this.insert = insert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.insertResponse insertResponse;
        
        public insertResponse1() {
        }
        
        public insertResponse1(ServiceNowWCF.JournalTableServiceNowReference.insertResponse insertResponse) {
            this.insertResponse = insertResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class update : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string elementField;
        
        private string element_idField;
        
        private string nameField;
        
        private string sys_idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
                this.RaisePropertyChanged("element");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string element_id {
            get {
                return this.element_idField;
            }
            set {
                this.element_idField = value;
                this.RaisePropertyChanged("element_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class updateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sys_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.update update;
        
        public updateRequest() {
        }
        
        public updateRequest(ServiceNowWCF.JournalTableServiceNowReference.update update) {
            this.update = update;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.updateResponse updateResponse;
        
        public updateResponse1() {
        }
        
        public updateResponse1(ServiceNowWCF.JournalTableServiceNowReference.updateResponse updateResponse) {
            this.updateResponse = updateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class deleteMultiple : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string elementField;
        
        private string element_idField;
        
        private string nameField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
                this.RaisePropertyChanged("element");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string element_id {
            get {
                return this.element_idField;
            }
            set {
                this.element_idField = value;
                this.RaisePropertyChanged("element_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
                this.RaisePropertyChanged("sys_created_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
                this.RaisePropertyChanged("sys_created_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class deleteMultipleResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteMultipleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.deleteMultiple deleteMultiple;
        
        public deleteMultipleRequest() {
        }
        
        public deleteMultipleRequest(ServiceNowWCF.JournalTableServiceNowReference.deleteMultiple deleteMultiple) {
            this.deleteMultiple = deleteMultiple;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteMultipleResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.deleteMultipleResponse deleteMultipleResponse;
        
        public deleteMultipleResponse1() {
        }
        
        public deleteMultipleResponse1(ServiceNowWCF.JournalTableServiceNowReference.deleteMultipleResponse deleteMultipleResponse) {
            this.deleteMultipleResponse = deleteMultipleResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class getKeys : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string elementField;
        
        private string element_idField;
        
        private string nameField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string valueField;
        
        private string @__use_viewField;
        
        private string @__encoded_queryField;
        
        private string @__limitField;
        
        private string @__first_rowField;
        
        private string @__last_rowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
                this.RaisePropertyChanged("element");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string element_id {
            get {
                return this.element_idField;
            }
            set {
                this.element_idField = value;
                this.RaisePropertyChanged("element_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
                this.RaisePropertyChanged("sys_created_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
                this.RaisePropertyChanged("sys_created_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string @__use_view {
            get {
                return this.@__use_viewField;
            }
            set {
                this.@__use_viewField = value;
                this.RaisePropertyChanged("__use_view");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string @__encoded_query {
            get {
                return this.@__encoded_queryField;
            }
            set {
                this.@__encoded_queryField = value;
                this.RaisePropertyChanged("__encoded_query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string @__limit {
            get {
                return this.@__limitField;
            }
            set {
                this.@__limitField = value;
                this.RaisePropertyChanged("__limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string @__first_row {
            get {
                return this.@__first_rowField;
            }
            set {
                this.@__first_rowField = value;
                this.RaisePropertyChanged("__first_row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string @__last_row {
            get {
                return this.@__last_rowField;
            }
            set {
                this.@__last_rowField = value;
                this.RaisePropertyChanged("__last_row");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class getKeysResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] sys_idField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sys_id", Order=0)]
        public string[] sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.getKeys getKeys;
        
        public getKeysRequest() {
        }
        
        public getKeysRequest(ServiceNowWCF.JournalTableServiceNowReference.getKeys getKeys) {
            this.getKeys = getKeys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKeysResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.getKeysResponse getKeysResponse;
        
        public getKeysResponse1() {
        }
        
        public getKeysResponse1(ServiceNowWCF.JournalTableServiceNowReference.getKeysResponse getKeysResponse) {
            this.getKeysResponse = getKeysResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class deleteRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sys_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class deleteRecordResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.deleteRecord deleteRecord;
        
        public deleteRecordRequest() {
        }
        
        public deleteRecordRequest(ServiceNowWCF.JournalTableServiceNowReference.deleteRecord deleteRecord) {
            this.deleteRecord = deleteRecord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRecordResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.deleteRecordResponse deleteRecordResponse;
        
        public deleteRecordResponse1() {
        }
        
        public deleteRecordResponse1(ServiceNowWCF.JournalTableServiceNowReference.deleteRecordResponse deleteRecordResponse) {
            this.deleteRecordResponse = deleteRecordResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class get : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sys_idField;
        
        private string @__use_viewField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string @__use_view {
            get {
                return this.@__use_viewField;
            }
            set {
                this.@__use_viewField = value;
                this.RaisePropertyChanged("__use_view");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class getResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string elementField;
        
        private string element_idField;
        
        private string nameField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
                this.RaisePropertyChanged("element");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string element_id {
            get {
                return this.element_idField;
            }
            set {
                this.element_idField = value;
                this.RaisePropertyChanged("element_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
                this.RaisePropertyChanged("sys_created_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
                this.RaisePropertyChanged("sys_created_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.get get;
        
        public getRequest() {
        }
        
        public getRequest(ServiceNowWCF.JournalTableServiceNowReference.get get) {
            this.get = get;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.getResponse getResponse;
        
        public getResponse1() {
        }
        
        public getResponse1(ServiceNowWCF.JournalTableServiceNowReference.getResponse getResponse) {
            this.getResponse = getResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class getRecords : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string elementField;
        
        private string element_idField;
        
        private string nameField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_idField;
        
        private string valueField;
        
        private string @__use_viewField;
        
        private string @__encoded_queryField;
        
        private string @__limitField;
        
        private string @__first_rowField;
        
        private string @__last_rowField;
        
        private string @__order_byField;
        
        private string @__order_by_descField;
        
        private string @__exclude_columnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
                this.RaisePropertyChanged("element");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string element_id {
            get {
                return this.element_idField;
            }
            set {
                this.element_idField = value;
                this.RaisePropertyChanged("element_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
                this.RaisePropertyChanged("sys_created_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
                this.RaisePropertyChanged("sys_created_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string @__use_view {
            get {
                return this.@__use_viewField;
            }
            set {
                this.@__use_viewField = value;
                this.RaisePropertyChanged("__use_view");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string @__encoded_query {
            get {
                return this.@__encoded_queryField;
            }
            set {
                this.@__encoded_queryField = value;
                this.RaisePropertyChanged("__encoded_query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string @__limit {
            get {
                return this.@__limitField;
            }
            set {
                this.@__limitField = value;
                this.RaisePropertyChanged("__limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string @__first_row {
            get {
                return this.@__first_rowField;
            }
            set {
                this.@__first_rowField = value;
                this.RaisePropertyChanged("__first_row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string @__last_row {
            get {
                return this.@__last_rowField;
            }
            set {
                this.@__last_rowField = value;
                this.RaisePropertyChanged("__last_row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string @__order_by {
            get {
                return this.@__order_byField;
            }
            set {
                this.@__order_byField = value;
                this.RaisePropertyChanged("__order_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string @__order_by_desc {
            get {
                return this.@__order_by_descField;
            }
            set {
                this.@__order_by_descField = value;
                this.RaisePropertyChanged("__order_by_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string @__exclude_columns {
            get {
                return this.@__exclude_columnsField;
            }
            set {
                this.@__exclude_columnsField = value;
                this.RaisePropertyChanged("__exclude_columns");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/sys_journal_field")]
    public partial class getRecordsResponseGetRecordsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string elementField;
        
        private string element_idField;
        
        private string nameField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
                this.RaisePropertyChanged("element");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string element_id {
            get {
                return this.element_idField;
            }
            set {
                this.element_idField = value;
                this.RaisePropertyChanged("element_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
                this.RaisePropertyChanged("sys_created_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
                this.RaisePropertyChanged("sys_created_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        public ServiceNowWCF.JournalTableServiceNowReference.getRecords getRecords;
        
        public getRecordsRequest() {
        }
        
        public getRecordsRequest(ServiceNowWCF.JournalTableServiceNowReference.getRecords getRecords) {
            this.getRecords = getRecords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecordsResponse", Namespace="http://www.service-now.com/sys_journal_field", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getRecordsResult", IsNullable=false)]
        public ServiceNowWCF.JournalTableServiceNowReference.getRecordsResponseGetRecordsResult[] getRecordsResponse1;
        
        public getRecordsResponse() {
        }
        
        public getRecordsResponse(ServiceNowWCF.JournalTableServiceNowReference.getRecordsResponseGetRecordsResult[] getRecordsResponse1) {
            this.getRecordsResponse1 = getRecordsResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceNowSoapChannel : ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNowSoapClient : System.ServiceModel.ClientBase<ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap>, ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap {
        
        public ServiceNowSoapClient() {
        }
        
        public ServiceNowSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNowSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNowSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNowSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceNowWCF.JournalTableServiceNowReference.insertResponse1 ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap.insert(ServiceNowWCF.JournalTableServiceNowReference.insertRequest request) {
            return base.Channel.insert(request);
        }
        
        public ServiceNowWCF.JournalTableServiceNowReference.insertResponse insert(ServiceNowWCF.JournalTableServiceNowReference.insert insert1) {
            ServiceNowWCF.JournalTableServiceNowReference.insertRequest inValue = new ServiceNowWCF.JournalTableServiceNowReference.insertRequest();
            inValue.insert = insert1;
            ServiceNowWCF.JournalTableServiceNowReference.insertResponse1 retVal = ((ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap)(this)).insert(inValue);
            return retVal.insertResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceNowWCF.JournalTableServiceNowReference.updateResponse1 ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap.update(ServiceNowWCF.JournalTableServiceNowReference.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public ServiceNowWCF.JournalTableServiceNowReference.updateResponse update(ServiceNowWCF.JournalTableServiceNowReference.update update1) {
            ServiceNowWCF.JournalTableServiceNowReference.updateRequest inValue = new ServiceNowWCF.JournalTableServiceNowReference.updateRequest();
            inValue.update = update1;
            ServiceNowWCF.JournalTableServiceNowReference.updateResponse1 retVal = ((ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap)(this)).update(inValue);
            return retVal.updateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceNowWCF.JournalTableServiceNowReference.deleteMultipleResponse1 ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap.deleteMultiple(ServiceNowWCF.JournalTableServiceNowReference.deleteMultipleRequest request) {
            return base.Channel.deleteMultiple(request);
        }
        
        public ServiceNowWCF.JournalTableServiceNowReference.deleteMultipleResponse deleteMultiple(ServiceNowWCF.JournalTableServiceNowReference.deleteMultiple deleteMultiple1) {
            ServiceNowWCF.JournalTableServiceNowReference.deleteMultipleRequest inValue = new ServiceNowWCF.JournalTableServiceNowReference.deleteMultipleRequest();
            inValue.deleteMultiple = deleteMultiple1;
            ServiceNowWCF.JournalTableServiceNowReference.deleteMultipleResponse1 retVal = ((ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap)(this)).deleteMultiple(inValue);
            return retVal.deleteMultipleResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceNowWCF.JournalTableServiceNowReference.getKeysResponse1 ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap.getKeys(ServiceNowWCF.JournalTableServiceNowReference.getKeysRequest request) {
            return base.Channel.getKeys(request);
        }
        
        public ServiceNowWCF.JournalTableServiceNowReference.getKeysResponse getKeys(ServiceNowWCF.JournalTableServiceNowReference.getKeys getKeys1) {
            ServiceNowWCF.JournalTableServiceNowReference.getKeysRequest inValue = new ServiceNowWCF.JournalTableServiceNowReference.getKeysRequest();
            inValue.getKeys = getKeys1;
            ServiceNowWCF.JournalTableServiceNowReference.getKeysResponse1 retVal = ((ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap)(this)).getKeys(inValue);
            return retVal.getKeysResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceNowWCF.JournalTableServiceNowReference.deleteRecordResponse1 ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap.deleteRecord(ServiceNowWCF.JournalTableServiceNowReference.deleteRecordRequest request) {
            return base.Channel.deleteRecord(request);
        }
        
        public ServiceNowWCF.JournalTableServiceNowReference.deleteRecordResponse deleteRecord(ServiceNowWCF.JournalTableServiceNowReference.deleteRecord deleteRecord1) {
            ServiceNowWCF.JournalTableServiceNowReference.deleteRecordRequest inValue = new ServiceNowWCF.JournalTableServiceNowReference.deleteRecordRequest();
            inValue.deleteRecord = deleteRecord1;
            ServiceNowWCF.JournalTableServiceNowReference.deleteRecordResponse1 retVal = ((ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap)(this)).deleteRecord(inValue);
            return retVal.deleteRecordResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceNowWCF.JournalTableServiceNowReference.getResponse1 ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap.get(ServiceNowWCF.JournalTableServiceNowReference.getRequest request) {
            return base.Channel.get(request);
        }
        
        public ServiceNowWCF.JournalTableServiceNowReference.getResponse get(ServiceNowWCF.JournalTableServiceNowReference.get get1) {
            ServiceNowWCF.JournalTableServiceNowReference.getRequest inValue = new ServiceNowWCF.JournalTableServiceNowReference.getRequest();
            inValue.get = get1;
            ServiceNowWCF.JournalTableServiceNowReference.getResponse1 retVal = ((ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap)(this)).get(inValue);
            return retVal.getResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceNowWCF.JournalTableServiceNowReference.getRecordsResponse ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap.getRecords(ServiceNowWCF.JournalTableServiceNowReference.getRecordsRequest request) {
            return base.Channel.getRecords(request);
        }
        
        public ServiceNowWCF.JournalTableServiceNowReference.getRecordsResponseGetRecordsResult[] getRecords(ServiceNowWCF.JournalTableServiceNowReference.getRecords getRecords1) {
            ServiceNowWCF.JournalTableServiceNowReference.getRecordsRequest inValue = new ServiceNowWCF.JournalTableServiceNowReference.getRecordsRequest();
            inValue.getRecords = getRecords1;
            ServiceNowWCF.JournalTableServiceNowReference.getRecordsResponse retVal = ((ServiceNowWCF.JournalTableServiceNowReference.ServiceNowSoap)(this)).getRecords(inValue);
            return retVal.getRecordsResponse1;
        }
    }
}
